### PR TITLE
CCTRI 21: Remove sighting and sighting_ref endpoints

### PR DESCRIPTION
**Pull request by AlinaBlahun**

### CODE REVIEW

**Comment by gdavoian** [comment]
Do we have to do it right now? Those endpoints aren't marked as deprecated and/or deleted from the documentation yet.

**Comment by cawabanga2811** [comment]
We need to do it cos M request it.

**Comment by gdavoian** [comment]
Please merge `develop` into this branch and merge all conflicts. Also don't forget to remove the corresponding tests from `test_deliberate.py`.

**Comment by AlinaBlahun** [comment]
@gdavoian Done, thanks

**Pull request merged**
